Update w8-s8-c2-game.md
flotpython/course pull request #49
Opened 2021-01-27 10:35 UTC by avast2008live

2021-01-27 10:36 UTC, avast2008live commented
J'avais du oublié une étape

2021-01-27 18:51 UTC, parmentelat requested changes
je ne vais pas trop avoir le temps de tester, mais à premiere vue en lisant le code il y a un souci avec un nouvel attribut  finished qui n'est pas initialisé, ou bien j'ai raté quelque chose ?

2021-01-27 18:51 UTC, parmentelat commented on w8/w8-s8-c2-game.md
>  * 1 seconde après le début une instance de `players.py 2`
pas grave, mais là il faudrait ajouter une ligne pour décrire le troisième jeu

2021-01-27 18:51 UTC, parmentelat commented on w8/w8-s8-c2-game.md
> +        if self.running == 0 and self.finished == self.to_be_run:
là par contre je suis un peu perdu, d'où vient self.finished ? 
cet attribut n'existe pas dans ma version ?!?

c'est embêtant car je ne vais pas avoir le temps de tester tout ça

2021-01-28 09:00 UTC, avast2008live commented
Désolé mais j'avais oublié d'insérer l'initialisation de cette variable et sa mise à jour dans mes modifications initiales.
C'est fait dans le deuxième commit

2021-01-28 09:09 UTC, merged

2021-01-28 09:09 UTC, parmentelat commented
ça m'a l'air correct, allons-y