w2-s2-x1-expressions-regulieres.md / Exercice - niveau intermédiaire (1) ne s'exécutait pas tel quel en local
flotpython/course pull request #55
Opened 2021-08-31 09:40 UTC by ahjun001

Dans w2-s2-x1-expressions-regulieres.md / Exercice - niveau intermédiaire (1), je suggère: 

(i) from **modules**.corrections.regexp_pythonid

et (ii)  il faut ajouter un sous-répertoire soft link sur le répertoire 'modules'

ensuite: (iii)
$ pip install nbautoeval    # nécessaire pour éxécuter l'exemple en local

2021-08-31 13:09 UTC, parmentelat requested changes
malheureusement je ne peux pas merger ça en l'état

2021-08-31 13:09 UTC, parmentelat commented on requirements.txt
> +nbautoeval
ok pour ça

2021-08-31 13:09 UTC, parmentelat commented on w2/modules
> +/home/perubu/Desktop/MOOC_Python3/wip_course/modules
par contre ceci est un chemin qui n'est. valide que sur votre ordi !

2021-08-31 13:09 UTC, parmentelat commented on w2/w2-s2-x1-expressions-regulieres.md
> +orig_nbformat: 1
je ne pense pas que ça suis nécessaire, si ?

2021-08-31 13:09 UTC, parmentelat commented on w2/w2-s2-x1-expressions-regulieres.md
> +from modules.corrections.regexp_pythonid import exo_pythonid
si j'adopte ça, l'exercice ne marchera plus dans le MOOC !
en fait ce qu'on fait sur la plateforme de notebooks qui est derrière fun-mooc, c'est de définir la variable `PYTHONPATH` pour qu'elle pointe vers le dossier `modules` à la racine du repo; je pense qu'en faisant ça de votre coté aussi ça va marcher bcp mieux (même si, je sais bien, on dit dans le cours de n'utiliser `PYTHONPATH` que à bon escient ;)

2021-09-02 03:39 UTC, ahjun001 commented on w2/modules
> +/home/perubu/Desktop/MOOC_Python3/wip_course/modules
oui, la solution avec PYTHONPATH fonctionne et ceci est maintenant inutile

2021-09-02 03:40 UTC, ahjun001 commented on w2/w2-s2-x1-expressions-regulieres.md
> +from modules.corrections.regexp_pythonid import exo_pythonid
Effectivement, l'exercice ... et les suivants que je n'avais pas encore abordés, fonctionne avec <code>PYTHONPATH</code> pointant sur <code>modules</code> 
L'ajout d'un lien vers <code>module</code> n'est donc plus nécessaire

2021-09-02 06:13 UTC, parmentelat commented on w2/w2-s2-x1-expressions-regulieres.md
> +from modules.corrections.regexp_pythonid import exo_pythonid
du oup il vous faut enlever cet ajout dans l' import

2021-09-02 06:15 UTC, parmentelat commented on w2/w2-s2-x1-expressions-regulieres.md
> +orig_nbformat: 1
je préfère éviter de modifier les métadata

2021-09-02 08:50 UTC, ahjun001 commented on w2/w2-s2-x1-expressions-regulieres.md
> +from modules.corrections.regexp_pythonid import exo_pythonid
Je pense l'avoir maintenant enlevé

2021-09-02 09:12 UTC, parmentelat commented
lgtm

2021-09-02 09:12 UTC, merged